SELECT dbo.FN_GET_TAMANHO_NM_CIDADE(1)

SELECT dbo.FN_GET_CARGOS_MAIORES_QUE(1000)

SELECT dbo.FN_GET_ENDERECO_COMPLETO_BY_ENDERECO_ID(1)

SELECT dbo.FN_GET_DADOS_BASICOS_FUNCIONARIO(20180057)

SELECT dbo.FN_GET_CLASSE_BY_ID(1)

SELECT dbo.FN_GET_NUM_ALA_BY_ID(1)

SELECT dbo.FN_GET_TIPO_CONTAINER(1)

SELECT dbo.FN_GET_NOME_ESPECIE_ANIMAL(1)

SELECT dbo.FN_GET_DATA_CONSULTA_BY_ID(1)

SELECT dbo.FN_GET_DATA_LIMPEZA_BY_ID(1)