-- Created by: João Felipe Fonseca Nascimento
-- joao.nascimento98@academico.ifs.edu.br - 2020

USE Zoboomafoo

GO

SELECT * FROM FN_CONSULTAR_CIDADES (1)

SELECT * FROM FN_CONSULTAR_CARGOS(1)

SELECT * FROM FN_CONSULTAR_ENDERECOS(1)

SELECT * FROM FN_CONSULTAR_FUNCIONARIOS (1)

SELECT * FROM FN_CONSULTAR_FUNCIONARIOS (20180057)

SELECT * FROM FN_CONSULTAR_CLASSES(1)

SELECT * FROM FN_CONSULTAR_ALAS(1)

SELECT * FROM FN_CONSULTAR_CONTEINERS(1)

SELECT * FROM FN_CONSULTAR_ANIMAIS(1)

SELECT * FROM FN_CONSULTAR_HISTORICO_CONSULTAS(1)

SELECT * FROM FN_CONSULTAR_LIMPEZAS(1)